repos:
  - name: ScaledTest
    url: https://github.com/example/ScaledTest
    workflow_path: workflows/feature.yaml
    workers: 2
    names:
      - furiosa
      - rictus
    prefix: st

  - name: citadel
    url: https://github.com/example/citadel
    workflow_path: workflows/feature.yaml
    workers: 2
    names:
      - nux
      - dementus
    prefix: ct

max_total_workers: 4
handoff_token_threshold: 100000
